version: '3'
services:
  influxdb:
    image: influxdb
    ports:
    - "8086:8086"
    environment:
      INFLUXDB_ADMIN_USER: "${INFLUXDB_USERNAME}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_PASSWORD}"
    volumes:
    - influxdb-volume:/var/lib/influxdb
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    volumes:
    - mongodb-volume:/data/db
volumes:
  influxdb-volume: {}
  mongodb-volume: {}
